---
- name: grab boto version
  command: python -c 'import boto3; print(boto3.__version__)'
  register: py_cmd

- name: make sure we are running correct boto version
  assert:
    that:
    - py_cmd.stdout.startswith('1.7')

- name: check for underscores in workshop name
  fail:
    msg: "Amazon AWS does not allow underscores _ for s3 websites, please see https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html"
  when:
    - create_login_page is defined
    - create_login_page
    - "'_' in ec2_name_prefix"

- name: grab information about AWS user
  aws_caller_facts:
    region: "{{ ec2_region }}"
  register: whoami

- name: save username of AWS user
  set_fact:
     linklight_user: '{{ whoami.arn.split("/")[-1] }}'

- debug: msg='{{ whoami.arn.split("/")[-1] }}'
