- name: BIG-IP setup
  hosts: lb
  connection: local
  gather_facts: false
  
  tasks:

  - name: Create nodes
    bigip_node:
      server: "{{private_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      server_port: "8443"
      host: "{{item}}"
      name: "{{item}}"
      validate_certs: "no"
    loop:
     - "{{ hostvars[groups['webservers'][0]].ansible_host }}"
     - "{{ hostvars[groups['webservers'][1]].ansible_host }}"
