---

- name: GitLab Post | Obtain Access Token
  uri:
    url: http://gitlab.{{ ec2_name_prefix }}.{{ public_dns_zone}}/oauth/token
    method: POST
    validate_certs: no
    status_code: 200
    body_format: json
    headers:
      Content-Type: application/json
    body: >
      {
        "grant_type": "password",
        "username": "root",
        "password": "{{ admin_password }}"
      }
  register: gitlab_access_token

- debug:
    var: gitlab_access_token

- name: GitLab Post | Create local users via API
  uri:
    url: http://gitlab.{{ ec2_name_prefix }}.{{ public_dns_zone }}/api/v4/users
    method: POST
    validate_certs: no
    status_code:
      - 200
      - 201
      - 409
    body_format: json
    headers:
      Content-Type: application/json
      Authorization: Bearer {{ gitlab_access_token.json.access_token }}
    body: >
      {
        "username": "student{{ item }}",
        "password": "{{ admin_password }}",
        "name": "student{{ item }}",
        "email": "student{{ item }}@{{ public_dns_zone }}",
        "skip_confirmation": true
      }
    register: create_user
  with_sequence: count="{{ student_total }}"

- debug:
    var: create_user

- name: GitLab Post | Get local user information via API
  uri:
    url: http://gitlab.{{ ec2_name_prefix }}.{{ public_dns_zone}}/api/v4/users?username=student{{ item }}
    method: GET
    validate_certs: no
    status_code:
      - 200
      - 201
    headers:
      Content-Type: application/json
      Authorization: Bearer {{ gitlab_access_token.json.access_token }}
  with_sequence: count="{{ student_total }}"
  register: gitlab_local_users

- name: GitLab Post | Create Projects via API
  uri:
    url: http://gitlab.{{ ec2_name_prefix }}.{{ public_dns_zone}}/api/v4/projects/user/{{ item.json[0].id }}
    method: POST
    validate_certs: no
    status_code:
      - 200
      - 201
      - 409
      - 400
    body_format: json
    headers:
      Content-Type: application/json
      Authorization: Bearer {{ gitlab_access_token.json.access_token }}
    body: >
      {
        "name": "{{ item.json[0].name }}",
        "group": "{{ item.json[0].name }}",
        "issues_enabled": false,
        "wiki_enabled": false,
        "snippets_enabled": false
      }
  loop: "{{ gitlab_local_users.results }}"
  when: item.json is defined
