---
- name: SETUP TOWER FOR CLOSED LOOP INCIDENT MGMT DEMO
  hosts: cisco
  connection: local
  become: yes
  gather_facts: no
  vars:
    tower_username: "admin"
    tower_password: "ansible"

  tasks:

    - name: move playbooks to /var/lib/awx/projects/snow_demo
      copy:
        src: "{{playbook_dir}}/"
        dest: /var/lib/awx/projects/snow_demo/
      become: yes
      become_method: sudo
      become_user: awx
      run_once: true
      delegate_to: localhost

    - name: add project to tower
      tower_project:
        name: SNOW_CL
        local_path: snow_demo
        organization: Default
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: https://localhost
        tower_verify_ssl: no
      run_once: true
      delegate_to: localhost

    - name: add servicenow custom cred
      tower_credential_type:
        name: "SNOW_CL Credential"
        description: Credential type for SNOW
        inputs: "{{ lookup('file', playbook_dir + '/custom_cred/inputs.yml') | from_yaml }}"
        injectors: "{{ lookup('file', playbook_dir + '/custom_cred/injector.yml') | from_yaml }}"
        state: present
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: https://localhost
        validate_certs: false

    - name: add job template - compliance check
      tower_job_template:
        name: "SNOW-Demo-Compliance-Check"
        job_type: run
        inventory: "Workshop Inventory"
        project: "SNOW_CL"
        playbook: snow_incident.yaml
        credential: "SNOW_CL Credential"
        state: "present"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: https://localhost
        tower_verify_ssl: no
      run_once: true
      delegate_to: localhost

    - name: ADD A JOB TEMPLATE - COMPLIANCE FIX
      tower_job_template:
        name: "SNOW-Demo-Compliance-Fix"
        job_type: run
        inventory: "SNOW_CL Inventory"
        project: "SNOW_CL"
        playbook: fix_banner.yaml
        credential: "SNOW_CL Credential"
        state: "present"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_host: https://localhost
        tower_verify_ssl: no
        ask_extra_vars: True
        extra_vars_path: ./snow_demo2/extra_vars.yaml
      run_once: true
      delegate_to: localhost
