---
- block:
  - name: Download Microsoft Visual C++ Redistributable Packages needed for SmartConsole async
    win_chocolatey:
      name:
        - vcredist2010
        - vcredist2012
      state: present
    async: "{{ windows_async_timeout }}"
    poll: 0
    register: download_visual_cpp_async

  - name: Wait for Download Microsoft Visual C++ async
    async_status:
      jid: "{{ download_visual_cpp_async.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 30

  - name: Ensure the required NuGet package provider version is installed async
    win_shell: Find-PackageProvider -Name Nuget -ForceBootstrap -IncludeDependencies -Force
    async: "{{ windows_async_timeout }}"
    poll: 0
    register: ensure_nuget_async

  - name: Install Pscx needed for unzip step later async
    win_psmodule:
      name: pscx
      allow_clobber: true
    async: "{{ windows_async_timeout }}"
    poll: 0
    register: install_pscx_async

  - name: Wait for Windows async tasks (smartconsole)
    async_status:
      jid: "{{ item['ansible_job_id'] }}"
    register: wait_for_async_tasks
    until: wait_for_async_tasks.finished
    retries: "{{ windows_async_timeout }}"
    loop:
      - "{{ ensure_nuget_async }}"
      - "{{ install_pscx_async }}"

  - name: Check if SmartConsole is downloaded
    win_stat:
      path: C:\Temp\SmartConsole.exe
    register: smartconsole

  - name: Download SmartConsole to specified path only if modified
    win_get_url:
      url: https://s3.amazonaws.com/linklight.securityautomation/Check_Point_SmartConsole_R80_20_jumbo_HF_B055_Win.exe
      dest: C:\Temp\SmartConsole.exe
      checksum: 424bd9ccac118c5a9c9e006b89f21d0a8b4f944b
      force: yes
    when: not smartconsole.stat.exists
    register: win_get_smartconsole
    until: win_get_smartconsole is success
    retries: 5

  - name: Unpack SmartConsole archive
    win_unzip:
      src: C:\Temp\SmartConsole.exe
      dest: C:\Temp\SmartConsole
      creates: C:\Temp\SmartConsole\SmartConsole.exe

  - name: Copy installer answer file to appropriate place
    win_copy:
      src: setup.iss
      dest: C:\Temp\SmartConsole\setup.iss

  - name: Execute SmartConsole installer
    win_command: C:\Temp\SmartConsole\SmartConsole.exe -s setup.iss


  ignore_errors: yes

