- name: Launch BIG-IP CFT
  cloudformation:
   stack_name: "{{ ec2_name_prefix }}-student{{item}}-f5"
   state: "present"
   region: "{{ ec2_region }}"
   disable_rollback: no
   template_url: "https://s3.amazonaws.com/f5-cft/f5-existing-stack-hourly-1nic-bigip.template"
   template_parameters:
    subnet1Az1: "{{ ec2_vpc_subnet_id }}"
    Vpc: "{{ec2_vpc_id}}"
    restrictedSrcAddress: "0.0.0.0/0"
    restrictedSrcAddressApp: "0.0.0.0/0"
    sshKey: "{{ ec2_name_prefix }}-key"
    imageName: "Good25Mbps"
   validate_certs: "no"
   tags:
     Name: "{{ ec2_name_prefix }}-student{{item}}-f5"
     AnsibleName: "{{ ec2_name_prefix }}-student{{item}}-f5"
     Workshop_f5: "{{ec2_name_prefix}}-f5"
     Workshop: "{{ec2_name_prefix}}"
     Index: "{{ item }}"
     Student: "student{{item}}"
     Username: "{{ linklight_user }}"
     Info: "Username that provisioned this-> {{ linklight_user }}"
     Linklight: "This was provisioned through the linklight provisioner"
     Students: "{{student_total}}"
  register: stack
  async:
  with_sequence: count="{{ student_total }}"
