- name: include splunk playbook
  import_playbook: splunk.yml
  when: security_console == 'splunk'

- name: INSTALL AND CONFIGURE SNORT
  hosts: snort
  become: true
  vars:
    ids_config_snort_version: '2.9.13'
    ids_install_provider: "snort"
    ids_install_normalize_logs: True
    ids_install_snort_user: root
    ids_install_snort_group: root
  tasks:
    - name: Install Pre Reqs for IDS
      block:
        - name: setup epel for snort ecosystem rule lifecycling
          include_role:
            name: "geerlingguy.repo-epel"
        - name: package pre-reqs are installed
          package:
            state: present
            name:
              - libselinux-python
              - python2-idstools

        - name: set selinux permissve because of policy issue that breaks snort
          selinux:
            policy: targeted
            state: permissive

    - name: Install IDS
      block:
        - name: import ids_install role
          include_role:
            name: "ansible_security.ids_install"
        - name: import ids_config role
          include_role:
            name: "ansible_security.ids_config"

- name: SETUP WINDOWS WORKSTATION
  hosts: windows
  roles:
    - role: windows_ws_setup

- name: SETUP CHECKPOINT ENVIRONMENT
  hosts: localhost
  become: no
  connection: local
  gather_facts: no
  roles:
    - role: cp_setup
