---
- name: Populate Tower
  hosts: control_nodes
  gather_facts: true
  become: true

  tasks:
    - name: Create Tower student resources
      include_role:
        name: populate_tower
        tasks_from: windows.yml
      when:
        - towerinstall is defined
        - towerinstall|bool

- name: Configure GitLab Host
  hosts: gitlab
  become: true
  gather_facts: true
  tags:
    - gitlab
  tasks:
    - name: old common fix by sean
      include_role:
        name: gitlab-server
        tasks_from: old-common.yml
    - include_role:
        name: geerlingguy.gitlab
    - include_role:
        name: gitlab-server

- name: Configure GitLab client
  hosts: control_nodes
  become: true
  gather_facts: true
  tags:
    - git
  roles:
    - gitlab-client
