# - name: Clone lightbulb
#   git:
#     accept_hostkey: yes
#     clone: yes
#     dest: /home/{{ username }}/lightbulb
#     repo: https://github.com/ansible/lightbulb.git
#     force: yes
#   become_user: "{{ username }}"

# - name: Remove things that students don't need
#   file:
#     state: absent
#     path: /home/{{ username }}/lightbulb/{{ item }}
#   with_items:
#     - aws_lab_setup
#     - resources
#     - Vagrantfile
#     - README.md

- name: Create lab inventory directory
  file:
    state: directory
    path: "/home/{{ username }}/devops-workshop/lab_inventory"
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes

- name: Put student inventory in proper spot
  copy:
    src: ./{{ec2_name_prefix}}/{{ username }}-instances.txt
    dest: "/home/{{ username }}/devops-workshop/lab_inventory/hosts"
    owner: "{{ username }}"
    group: "{{ username }}"
  when: username in inventory_hostname

- name: ADD THE EXTRAS REPO
  shell: yum-config-manager --enable rhui-REGION-rhel-server-extras

- name: ENSURE THAT DOCKER IS INSTALLED
  yum:
    name: docker
    state: present

- name: ENSURE THAT DOCKER DAEMON IS STARTED
  service:
    name: docker
    state: started
