---
- name: Create lab inventory directory
  file:
    state: directory
    path: /home/{{ username }}/lab_inventory

- name: Put student inventory in proper spot
  copy:
    src: ./{{ec2_name_prefix}}/{{ username }}-instances.txt
    dest: /home/{{ username }}/lab_inventory/hosts
    owner: "{{ username }}"
    group: "{{ username }}"
  when: username in inventory_hostname

- name: setup /etc/hosts file per student
  copy:
    src: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ username }}-etchosts.txt"
    dest: "/etc/hosts"
    owner: "{{ username }}"
    group: "{{ username }}"
